### ISSUE TITLE
Does this control multiple chrome casts?

### ISSUE THREAD

**Issue by drparham** [Pizzaface/Alexa-Chromecast-Skill#1]
I want to be able to control chromecast audio's for multiroom audio control.
Like, 
"Alexa play classic rock in living room"

**Comment by Pizzaface** [comment]
Thanks for the request!

This feature is upcoming, and will be based on some code I've already begun
to write. i'll be sure to keep you updated!

**Comment by drparham** [comment]
Excellent. I was searching the internet trying to find a solution to that problem. This was the closest thing i could find.

**Comment by Pizzaface** [comment]
I've committed some Test Code to "test-branch" under commit 91080c7. It's untested with actual ChromeCasts (as I am out of town), but from the little testing I did do, it might do what you want. This commit also includes Google Play Music Functionality.

**Comment by drparham** [comment]
Great, i'll go pick up a few chromecasts this weekend and give this a try.

**Comment by drparham** [comment]
Working on getting this setup. 

Have the LAMBDA part setup, however setting up the skill in Alexa Developer, when creating the utterance, and intent schema, i get the error:

"Error: There was a problem with your request: Unknown slot type 'TYPE_OF_MEDIA' for slot 'media'"

It's related to the intent schema referencing it, but unsure what i should be doing to create the slot type?

**Comment by Pizzaface** [comment]
Try adding the Custom Slot "TYPE_OF_MEDIA" with values
album
song
artist

**Comment by drparham** [comment]
great thank you for the fast response!

**Comment by Pizzaface** [comment]
I should note, that there is a new version of this coming, so I am no longer supporting this project. I'll be sure to keep you updated.

**Comment by drparham** [comment]
Yeah let me know, I made some modifications to the chromecastPlayVideo.py to use pymysql instead of the MySQLdb as i was having problems getting the dependencies to install. 

Let me know how i can help, this is an important modification for my home automation/audio setup.
