### ISSUE TITLE
Alexa Chromecast Netflix/CrunchyRoll support

### ISSUE THREAD

**Issue by msaroufim** [Pizzaface/Alexa-Chromecast-Skill#4]
Am wondering if there any plans down the line to make this work for Netflix or CrunchyRoll. 

Don't have much Alexa dev experience but am happy to help under your guidance

**Comment by Pizzaface** [comment]
Hey Mark!

Unfortunately, this is more limited by the package we use to interface with
the Chromecast more than anything. With YouTube, we grab a streaming URL
that we pass to the Chromecast and plays on the default player. Launching
apps is a bit tougher.

**Comment by msaroufim** [comment]
Understood. Thanks Pizzaface!
